version: "3.9"

services:
  kmp-builder:
    build:
      context: .
      dockerfile: Dockerfile.kmp
    container_name: kmp-dev
    volumes:
      - .:/app
      - ~/.android/sdk:/opt/android-sdk
      - ~/.gradle:/root/.gradle
    working_dir: /app
    environment:
      ANDROID_SDK_ROOT: /opt/android-sdk
    ports:
      - "8080:8080"
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kmp-backend
    working_dir: /usr/src/app
    volumes:
      - ./src/backend:/usr/src/app
    ports:
      - "8080:8080"
