version: "3.9"
services:
  kotlin-multiplatform-app-project:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      ANDROID_HOME: /opt/android-sdk
    tty: true
